### ISSUE TITLE
Add three help links to Getting Started subtab

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#66]
below the Send Test and Let's Go buttons pls add the same three links from the Help button on a Notification detail page

Text should be as follows with the name being the link:

User Guide:  A detailed description of the features and functions in the Echo for Salesforce notification system.

Quick Start Guide:  A quick reference guide to help you build, send, monitor, and review an Echo notification.

Training Video:  See the steps involved to build, send, monitor, and review an Echo notification.

the User Guide and Quick Start Guides are Documents (standard object) in the app so the ID will be different for each installed org. 

User Guide: https://c.ap1.content.force.com/servlet/servlet.FileDownload?file=01590000005iQBA
Quick Start: https://c.ap1.content.force.com/servlet/servlet.FileDownload?file=0159000000AdqeL
Training video: https://player.vimeo.com/video/108679299?title=0&#38;byline=0&#38;portrait=0&#38;autoplay=1

**Comment by stevenFulgham** [comment]
I have added the links in the dev org. Before I move it to Packaging I need more information about the dynamic nature of the links. Are these links in our org now or in packaging. Is this feature implemented anywhere else in the app? What part of the link is dynamic just the "?file=ID" or the whole link? Also, the page you're referring to "Notification detail page", could you give me a snapshot of that?

Thanks!

**Comment by jengler74** [comment]
Check out NotificationHelp.page. the whole page is just those three links. it's in dev and package, it's old code. It's not implemented anywhere else in the app

**Comment by stevenFulgham** [comment]
Alright I perused the "NotificationHelp" page and I have implemented the code the way they have it. The problem is that what you have at the top for the Quick Start and User Guide is not the same as what they have. Your file is pointing at a different document which I cant seem to find. I have an attached an image of the documents in the org. After you've tested my implementation, if you feel that it should be pointing at a different doc., please let me know which one.

Thanks

![screen shot 2016-05-20 at 3 00 51 pm](https://cloud.githubusercontent.com/assets/17146094/15439025/ff0665ec-1e9c-11e6-8c40-cff031aafcea.png)

**Comment by jengler74** [comment]
oops. The Quick Start is this one:

https://c.na30.content.force.com/servlet/servlet.FileDownload?file=01536000000ryDG

**Comment by jengler74** [comment]
pls make the two documents open in a new tab

**Comment by stevenFulgham** [comment]
Minor adjustment to the javascript and page opens in a new tab. You're ready to roll. I have also made the updates to Packaging as well.
