### ISSUE TITLE
Done button missing from all Setup Ass't steps

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#68]
![image](https://cloud.githubusercontent.com/assets/7884339/15377075/eb92842c-1d0d-11e6-912d-9ba62f4d5605.png)

can't progress to the next object without closing the window.

**Comment by jengler74** [comment]
same behavior for workflow

**Comment by stevenFulgham** [comment]
After I changed the anchor tags to apex outputLink link tags, the ids associated with the elements controlled by javascript broke. Basically Salesforce appends "$j_id0:" to the ids on elements which was breaking the javascript.

I used a class instead of the id and I also fixed the top navigation. It was not changing the step status of the Admin page for the same reasons. 

I have updated the Packaging Org as well.
