### ISSUE TITLE
change error message on missing Confirm Password

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#82]
When entering a new Echo Config, if the Confirm Password field is left null, the error message refers to the New Password field. 

Let's make the message:

"Confirm Password: You must enter a value"

![image](https://cloud.githubusercontent.com/assets/7884339/15549721/c656a1c0-2262-11e6-803d-fd8b89c6748b.png)

**Comment by stevenFulgham** [comment]
Changed text on server side to "Confirm Password" instead of "Repeat New Password". Updated Packaging.

**Comment by stevenFulgham** [comment]
The first time the password and confirm password are saved the values are persisted correctly.

![screen shot 2016-05-26 at 4 09 06 pm](https://cloud.githubusercontent.com/assets/17146094/15589061/1eb5ee46-235f-11e6-9165-8d8581f5ca75.png)

The second time the value for the "New password" is persisted as asterisks, which means it doesn't match the "Confirm Password" field.

![screen shot 2016-05-26 at 4 09 48 pm](https://cloud.githubusercontent.com/assets/17146094/15589132/78697a52-235f-11e6-9548-e93af8d463ac.png)

The problem was due to a property on the apex control (redisplay="true"). Once removed, everything work as expected.
