### ISSUE TITLE
Echo Configuration: Password Mismatch

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#88]
Save and Save And New Buttons are not working
1. Click on New Configuration 
2. Add all required value with New Password and Confirm Password are not same
   a. you can use JeremyCS as the username and 20000 for # of Recip 
3. Click on save button, receive an error message that passwords do not match
4. Now make New Password and Confirm Password the same
5. Save or Save And New button 

expected: submits new password
actual: error message persists, page seems unresponsive to the change in Confirm Password

**Comment by stevenFulgham** [comment]
The first time the password and confirm password are saved the values are persisted correctly.

![screen shot 2016-05-26 at 4 09 06 pm](https://cloud.githubusercontent.com/assets/17146094/15589061/1eb5ee46-235f-11e6-9165-8d8581f5ca75.png)

The second time the value for the "New password" is persisted as asterisks, which means it doesn't match the "Confirm Password" field.

![screen shot 2016-05-26 at 4 09 48 pm](https://cloud.githubusercontent.com/assets/17146094/15589132/78697a52-235f-11e6-9548-e93af8d463ac.png)

The problem was due to a property on the apex control (redisplay="true"). Once removed, everything work as expected.

Updated Packaging.
